export function aiGuideText(): string {
  return [
    "# vspec AI Guide",
    "",
    "## 가장 중요한 규칙: 모든 변경은 CLI로",
    "",
    "- **`specs/` 아래 파일을 Edit/Write 같은 파일 편집 도구로 직접 수정하지 않는다.**",
    "  spec의 생성·수정·삭제는 전부 `vspec` 명령으로만 한다.",
    "- 파일시스템은 지금(MVP)의 저장 방식일 뿐이다. vspec은 곧 원격 서버 데이터베이스로 옮겨가며,",
    "  그때 직접 파일 편집은 **불가능**해진다. 지금부터 CLI만으로 작업하면 그 전환이 매끄럽다.",
    "- 본문 작성은 `vspec usecase apply`가 1급 경로다. 내용은 네가 작성하되, 파일에 직접 쓰지 말고",
    "  stdin으로 CLI에 제출한다. CLI가 파싱·검증·정규화해서 저장한다 (원격 DB의 PUT/PATCH와 동일).",
    "",
    "## 작성 원칙",
    "",
    "- 사용자의 요청, PRD, 기존 문서가 한국어이면 use case 본문도 한국어로 작성한다.",
    "- 파일명, key, actor/stakeholder `name` 같은 식별자는 영문 kebab-case로 쓴다 (예: `user`, `cli-agent`).",
    "- **actor/stakeholder를 참조할 때는 display_name이 아니라 `name`(영문 slug)을 쓴다.** doctor는 `name`만 인식한다.",
    "  예: `1. **user** 계정을 연동한다.` (O) / `1. **사용자** 계정을 연동한다.` (X — display_name이라 인식 안 됨).",
    "- **title은 동사구(목표)로 쓴다.** 예: `주문을 생성한다`, `GitHub 계정을 연동한다`.",
    "  명사형 종결(`...등록`, `...확인`, `...생성`, `...주입`)은 피한다 — `...등록한다`처럼 동사로 끝낸다.",
    "- title, stakeholder interest, precondition, trigger, scenario step의 동작 텍스트, extension, guarantee, notes는 사용자의 언어를 따른다 (단, 위의 actor/stakeholder 참조 이름은 영문 slug).",
    "- 모든 scenario step은 E2E 테스트의 When/Then으로 옮길 수 있을 만큼 관찰 가능한 행동과 결과를 담는다.",
    "- `specs/glossary.md`의 Preferred Terms를 우선 사용하고 Avoid Terms의 모호한 표현을 피한다.",
    "",
    "## 기본 흐름",
    "",
    "1. 저장소 루트에서 `vspec init --key VSPEC`를 실행한다.",
    "2. 참조 actor를 `vspec actor create --name developer --display-name \"개발자\"`로 만든다.",
    "3. 참조 stakeholder를 `vspec stakeholder create --name vooster --display-name \"Vooster\"`로 만든다.",
    "4. `vspec usecase create --title \"유스케이스를 작성한다\" --primary-actor developer`로 use case 골격을 만든다.",
    "5. 본문은 `vspec usecase apply`로 채운다 — 섹션별로 `--section`을 쓰거나, 본문 전체를 한 번에 제출한다.",
    "6. frontmatter(상태/우선순위 등 메타데이터)는 `vspec usecase set`으로 바꾼다.",
    "7. `vspec doctor <KEY>`를 실행해 오류와 품질 경고를 확인한다. (`apply`는 검증 결과를 warnings로 함께 돌려준다.)",
    "8. 준비되면 `vspec export gherkin <KEY>`로 feature 파일을 만든다.",
    "",
    "## 본문 작성: `vspec usecase apply`",
    "",
    "내용은 stdin으로 전달한다. 두 가지 모드가 있다.",
    "",
    "- **섹션 하나만 교체** (부분 수정, 토큰 절약 — 권장 기본):",
    "  ```",
    "  vspec usecase apply UC-001 --section main-success <<'EOF'",
    "  1. **customer** 장바구니 항목을 확인한다.",
    "  2. **system** 주문을 기록한다.",
    "  EOF",
    "  ```",
    "- **본문 전체 교체** (`--section` 생략, 전면 재작성용):",
    "  ```",
    "  cat body.md | vspec usecase apply UC-001",
    "  ```",
    "",
    "`--section` 에 줄 수 있는 이름과 각 섹션이 기대하는 형식:",
    "",
    "| `--section` 값        | 내용 형식 (stdin)                                            |",
    "|-----------------------|-------------------------------------------------------------|",
    "| `blurb`               | 자유 텍스트 한두 문장 (맥락 설명)                            |",
    "| `stakeholders`        | `- **<name>**: <관심사> _(Protected by: <ref>)_` 줄 목록     |",
    "| `preconditions`       | `- <선행 조건>` 불릿 목록                                    |",
    "| `trigger`             | 유스케이스를 시작하는 이벤트 한 줄                           |",
    "| `main-success`        | `1. **<actor>** <동작>.` 번호 매긴 스텝 목록                 |",
    "| `extensions`          | 아래 Extensions 형식 블록                                    |",
    "| `success-guarantee`   | 성공 시 보장되는 관찰 가능한 결과                            |",
    "| `minimal-guarantee`   | 실패해도 보장되는 최소 결과                                  |",
    "| `notes`               | 자유 형식 메모                                               |",
    "",
    "주의: `--section`은 해당 섹션을 **통째로 교체**한다. stakeholders나 main-success처럼 목록형 섹션은",
    "유지하려는 기존 항목까지 포함해 전체 목록을 보내야 한다. 빈 내용을 보내면 그 섹션이 비워진다.",
    "(`title`은 frontmatter이므로 `vspec usecase set <KEY> --field title --value \"...\"`로 바꾼다.)",
    "",
    "## 유효한 enum 값",
    "",
    "아래 값 외에는 `vspec usecase set` 이 거절하므로 반드시 정확히 입력한다.",
    "",
    "| 필드       | 유효한 값                                    | 비고                                     |",
    "|------------|----------------------------------------------|------------------------------------------|",
    "| `level`    | USER_GOAL \\| SUMMARY \\| SUBFUNCTION          | CLI 플래그: user-goal\\|summary\\|subfunction |",
    "| `format`   | BRIEF \\| CASUAL \\| FULLY_DRESSED             | 작성 시작은 BRIEF, 모든 필드를 채우면 FULLY_DRESSED |",
    "| `status`   | DRAFT \\| IN_REVIEW \\| APPROVED \\| DEPRECATED | 기본값은 DRAFT                           |",
    "| `priority` | P0 \\| P1 \\| P2 \\| P3                         | CLI 플래그: p0\\|p1\\|p2\\|p3              |",
    "",
    "예시:",
    "",
    "```",
    "vspec usecase set UC-001 --field status --value IN_REVIEW",
    "vspec usecase set UC-001 --field priority --value P1",
    "vspec usecase set UC-001 --field level --value USER_GOAL",
    "```",
    "",
    "잘못된 값(예: `--value p1`, `--value in_review`)을 입력하면 CLI가 오류를 반환하고 파일은 변경되지 않는다.",
    "",
    "## Extensions(확장) 작성법",
    "",
    "Extension은 메인 성공 시나리오에서 벗어나는 분기 — 오류, 대안 흐름, 예외 — 를 정의한다.",
    "가장 흔한 혼동의 원인이므로 아래 규칙을 숙지한다.",
    "",
    "### 확장 포인트 ID 규칙",
    "",
    "- `3a` = 메인 시나리오 3번 스텝에서 분기하는 첫 번째 대안",
    "- `3b` = 동일 스텝에서 두 번째 대안",
    "- `*a` = 임의의 단계에서 발생할 수 있는 첫 번째 대안 (예: 세션 만료)",
    "- Outcome은 `SUCCESS | FAILURE | PARTIAL` 중 하나. 명시하지 않으면 기본값은 `FAILURE`.",
    "- 메인 시나리오로 복귀하면 Outcome 자유 텍스트에 `rejoins main at step N`을 적는다.",
    "",
    "### `apply --section extensions` 로 작성",
    "",
    "아래 블록을 그대로 stdin으로 보낸다 (Extensions 섹션 전체를 교체한다):",
    "",
    "```",
    "vspec usecase apply UC-001 --section extensions <<'EOF'",
    "### 3a. 결제 수단이 거절되면",
    "- 3a1. **system** 거절 사유를 표시한다.",
    "- 3a2. **customer** 다른 결제 수단을 선택한다.",
    "- (Outcome: FAILURE — 유스케이스를 종료한다.)",
    "",
    "### 3b. 재고가 부족하면",
    "- 3b1. **system** 재고 부족 메시지를 표시한다.",
    "- 3b2. **customer** 수량을 줄이거나 취소를 선택한다.",
    "- (Outcome: PARTIAL — rejoins main at step 2.)",
    "",
    "### *a. 세션이 만료되면",
    "- *a1. **system** 재로그인을 요구한다.",
    "- (Outcome: PARTIAL — rejoins main at step 2.)",
    "EOF",
    "```",
    "",
    "포맷 규칙:",
    "",
    "- 확장 헤더: `### <단계><글자>. <조건>` (예: `3a`, `3b`, `*a`)",
    "- 핸들링 스텝: `- <id>. **actor** <동작>.` (id는 `3a1`, `3a2`, `*a1` 등, actor는 영문 slug)",
    "- Outcome 줄: `- (Outcome: SUCCESS|FAILURE|PARTIAL — <자유 텍스트>)`",
    "- 메인 시나리오로 복귀하는 경우 자유 텍스트에 `rejoins main at step N` 형태로 적는다.",
    "- Outcome 줄을 생략하면 파서는 해당 확장을 `FAILURE`로 간주한다.",
    "",
    "## 인식되는 섹션 제목 (직접 편집용이 아니라 참조용)",
    "",
    "전체 본문을 `apply`로 보낼 때, 본문은 아래 제목들을 정확히 이 표기로 사용해야 파서가 인식한다.",
    "",
    "| 섹션 제목                        | `--section` 값        | 설명                           |",
    "|----------------------------------|-----------------------|--------------------------------|",
    "| `## Stakeholders and Interests`  | `stakeholders`        | 이해관계자와 관심사            |",
    "| `## Preconditions`               | `preconditions`       | 선행 조건                      |",
    "| `## Trigger`                     | `trigger`             | 유스케이스를 시작하는 이벤트   |",
    "| `## Main Success Scenario`       | `main-success`        | 메인 성공 시나리오 스텝 목록   |",
    "| `## Extensions`                  | `extensions`          | 확장(대안/예외) 시나리오       |",
    "| `## Success Guarantee`           | `success-guarantee`   | 성공 시 보장 조건              |",
    "| `## Minimal Guarantee`           | `minimal-guarantee`   | 실패 시에도 보장되는 최소 조건 |",
    "| `## Notes`                       | `notes`               | 자유 형식 메모                 |",
    "",
    "메인 시나리오 스텝 형식: `1. **<actor-name>** <동작>.` — 번호 + 굵은 actor `name`(영문 slug) + 동작. 동작은 사용자의 언어로, actor 이름은 영문 slug로 쓴다.",
    "",
    "작업 후에는 `vspec doctor <KEY>`로 검증한다. `apply`는 저장 직후 검증 결과를 warnings로 함께 돌려준다.",
    "",
    "다시 강조: `specs/` 파일을 직접 편집하지 않는다. 모든 추가·수정·삭제는 `vspec` 명령으로 한다.",
  ].join("\n");
}
